[package]
name = "procdump"
version = "0.1.0"
authors = ["Avi Weinstock <aweinstock314@gmail.com>"]

[dependencies]
argparse = "0.2.1"
byteorder = "0.5.3"
hex = "0.2.0"
libc = "0.2.16"
nom = "1.2.4"
rand = "0.3.14"
time = "0.1.35"

[features]
default = []
use_producerconsumer = []
